# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "redis_multi_list"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["James Richard"]
  s.date = "2013-02-08"
  s.description = "Create persistent, redis-backed arrays with a simple, familiar syntax"
  s.email = "ketzu@me.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Guardfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/redis_multi_list.rb",
    "lib/redis_multi_list/list.rb",
    "spec/redis_multi_list/list_spec.rb",
    "spec/redis_multi_list_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/byliner/redis_multi_list"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Easy Multi Dimensional Arrays in Redis"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redis>, [">= 0"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<guard>, ["~> 1.6.0"])
      s.add_development_dependency(%q<guard-rspec>, ["~> 1.2.0"])
      s.add_development_dependency(%q<rb-inotify>, ["~> 0.9.0"])
      s.add_development_dependency(%q<rb-fsevent>, ["~> 0.9.3"])
      s.add_development_dependency(%q<rb-fchange>, ["~> 0.0.6"])
    else
      s.add_dependency(%q<redis>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<guard>, ["~> 1.6.0"])
      s.add_dependency(%q<guard-rspec>, ["~> 1.2.0"])
      s.add_dependency(%q<rb-inotify>, ["~> 0.9.0"])
      s.add_dependency(%q<rb-fsevent>, ["~> 0.9.3"])
      s.add_dependency(%q<rb-fchange>, ["~> 0.0.6"])
    end
  else
    s.add_dependency(%q<redis>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<guard>, ["~> 1.6.0"])
    s.add_dependency(%q<guard-rspec>, ["~> 1.2.0"])
    s.add_dependency(%q<rb-inotify>, ["~> 0.9.0"])
    s.add_dependency(%q<rb-fsevent>, ["~> 0.9.3"])
    s.add_dependency(%q<rb-fchange>, ["~> 0.0.6"])
  end
end

